name: Strict CI

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  strict-lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: |
        yarn install --frozen-lockfile
      env:
        CI: true
    - uses: reviewdog/action-setup@v1

    - name: run tsc strict
      run: |
        yarn tsc --project tsconfig.strict.json --noEmit | reviewdog -f=tsc -diff="git diff master" -reporter=github-pr-check -fail-on-error -filter-mode=file
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: run eslint strict
      run: |
        yarn eslint --config ./.eslintrc.strict.js --ext .js,.ts --ignore-path .gitignore . | reviewdog -f=eslint -diff="git diff master" -reporter=github-pr-check -fail-on-error -filter-mode=file
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}